CREATE TABLE tokens
(
    token_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token    VARCHAR(255),
    user_id  BIGINT,
    CONSTRAINT pk_tokens PRIMARY KEY (token_id),
    CONSTRAINT uc_tokens_token UNIQUE (token),
    CONSTRAINT FK_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id)
);